"""add models for cart implementatoin

Revision ID: 1e45f2a7da16
Revises: ad5ce502d3f3
Create Date: 2025-04-08 15:11:36.876507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e45f2a7da16'
down_revision = 'ad5ce502d3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_user_id'), ['user_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_item_created_at'), ['created_at'], unique=False)

    op.drop_table('product_variations')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_category_id_fkey', 'category', ['category_id'], ['id'], ondelete='CASCADE')

    op.create_table('product_variations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('selling_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_variations_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_variations_pkey')
    )
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_created_at'))

    op.drop_table('cart_item')
    op.drop_table('product_variant')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_created_at'))

    op.drop_table('cart')
    # ### end Alembic commands ###
