"""empty message

Revision ID: 399b4dcf3762
Revises: 1a8a108e014e
Create Date: 2025-04-02 02:46:52.417154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399b4dcf3762'
down_revision = '1a8a108e014e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_menu_item', schema=None) as batch_op:
        batch_op.drop_column('ref_id')

    # ### end Alembic commands ###
