"""UPDATE length of description field in tag table

Revision ID: 8109b3cb5229
Revises: bec261377860
Create Date: 2025-02-05 14:49:35.030229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8109b3cb5229'
down_revision = 'bec261377860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
