"""add label field to the model 'NavMenuItem'

Revision ID: ad5ce502d3f3
Revises: 399b4dcf3762
Create Date: 2025-04-02 11:02:44.674060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5ce502d3f3'
down_revision = '399b4dcf3762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_menu_item', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
